apiVersion: apps/v1
kind: Deployment
metadata:
  name: webcv-deployment
spec:
  selector:
    matchLabels:
      app: webcv
  replicas: 3 # número deseado de réplicas
  template:
    metadata:
      labels:
        app: webcv
    spec:
      containers:
        - name: webcv
          image: andrejet55/webcv
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webcv-service
spec:
  selector:
    app: webcv
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: LoadBalancer # tipo de servicio que se creará
